disableConfigWatcher = false
earlyWindowControl = false
maxThreads = -1
versionCheck = true
debugOpenGl = false
defaultConfigPath = "defaultconfigs"
disableOptimizedDFU = true
earlyWindowProvider = "fmlearlywindow"
earlyWindowWidth = 854
earlyWindowHeight = 480
earlyWindowMaximized = false
earlyLoadingScreenTheme = ""
dependencyOverrides = {}
