import se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask
import org.gradle.api.attributes.java.TargetJvmVersion

buildscript {
	repositories {
		maven { url = 'https://files.minecraftforge.net/maven' }
		mavenCentral()
	}
	dependencies {
		classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.0.54'
	}
}

plugins {
	id 'java'
	id 'eclipse'
	id 'idea'
	id "maven-publish"
	id 'me.modmuss50.mod-publish-plugin' version '2.2.0'
	id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '3.1.2'
}
apply plugin: 'net.minecraftforge.gradle'
apply from: 'buildtools/ColoredOutput.gradle'
apply from: 'buildtools/AppleSiliconSupport.gradle'

//adds the build number to the end of the version string if on a build server
String build_number = System.getenv().BUILD_NUMBER
if (build_number == null) {
	build_number = '9999'
}

String semver = "${version_major}.${version_minor}.${version_patch}"

// these two are required for the java plugin to generate jar files with a version
version = "${semver}.${build_number}"
group = 'mezz.jei' // http://maven.apache.org/guides/mini/guide-naming-conventions.html

sourceSets {
	api {
		//The API has no resources
		resources.srcDirs = []
	}
	main {
		compileClasspath += sourceSets.api.output
		runtimeClasspath += sourceSets.api.output
	}
	test {
		//The test module has no resources
		resources.srcDirs = []
		compileClasspath += sourceSets.api.output
		runtimeClasspath += sourceSets.api.output
	}
}

configurations {
	apiImplementation.extendsFrom(implementation)
	apiRuntimeOnly.extendsFrom(runtimeOnly)
}

['testCompileClasspath', 'testRuntimeClasspath'].each { configurationName ->
	configurations.named(configurationName) {
		attributes.attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 17)
	}
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(JavaCompile).configureEach {
	options.release.set(8)
}

dependencies {
	minecraft([
			group  : "${project.forge_group}",
			name   : 'forge',
			version: "${project.minecraft_version}-${project.forge_version}"
	])
	testImplementation "org.junit.jupiter:junit-jupiter:6.1.3"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher:6.1.3"
	testImplementation "org.mockito:mockito-core:5.23.0"
}

minecraft {
	mappings channel: 'official', version: project.minecraft_version

	accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

	runs {
		client {
			property 'forge.logging.console.level', 'debug'
			workingDirectory file('run')
			mods {
				jei.sources((SourceSet[]) [sourceSets.main, sourceSets.api])
			}
		}
		server {
			property 'forge.logging.console.level', 'debug'
			workingDirectory file('run')
			mods {
				jei.sources((SourceSet[]) [sourceSets.main, sourceSets.api])
			}
		}
	}
}

def replaceResources = tasks.register("replaceResources", Copy) {
	it.outputs.upToDateWhen { false }
	//Copy it into the build dir
	it.from(sourceSets.main.resources) {
		include "META-INF/mods.toml"
		expand 'version': version, 'mc_version': minecraft_version_range, 'forge_version': forge_version_range, "loader_version": loader_version_range
	}
	it.into "$buildDir/resources/main/"
}

processResources {
	duplicatesStrategy(DuplicatesStrategy.FAIL)
	exclude('META-INF/mods.toml')
	configure { finalizedBy(replaceResources) }
}

classes.configure {
	dependsOn(replaceResources)
}

javadoc {
	source = [sourceSets.main.allJava, sourceSets.api.allJava]
	// prevent java 8's strict doclint for javadocs from failing builds
	options.addStringOption('Xdoclint:none', '-quiet')
}

def makeChangelog = tasks.register('makeChangelog', GitChangelogTask) {
	def output = layout.buildDirectory.file('changelog.html')
	fromRepo.set(projectDir.absolutePath)
	file.set(output.get().asFile)
	untaggedName.set("Current release ${project.version}")
	fromRevision.set('2fe051cf727adce1be210a46f778aa8fe031331e')
	toRevision.set('HEAD')
	templateContent.set(file('changelog.mustache').getText('UTF-8'))
	outputs.file(output)
	outputs.upToDateWhen { false }
}

def makeMarkdownChangelog = tasks.register('makeMarkdownChangelog', GitChangelogTask) {
	def output = layout.buildDirectory.file('changelog.md')
	fromRepo.set(projectDir.absolutePath)
	file.set(output.get().asFile)
	untaggedName.set("Current release ${project.version}")
	fromRevision.set('61d3bcb0d37e12dc3872bec62ef831dbe7699c59')
	toRevision.set('HEAD')
	templateContent.set(file('changelog-markdown.mustache').getText('UTF-8'))
	outputs.file(output)
	outputs.upToDateWhen { false }
}

def changelogHtml = providers.provider { layout.buildDirectory.file('changelog.html').get().asFile.getText('UTF-8') }
def changelogMarkdown = providers.provider { layout.buildDirectory.file('changelog.md').get().asFile.getText('UTF-8') }

publishMods {
	file.set(tasks.jar.archiveFile)
	version.set(project.version.toString())
	changelog.set(changelogMarkdown)
	type.set(BETA)
	displayName.set("${project.version} for Forge ${minecraft_version}")
	modLoaders.add('forge')

	curseforge {
		projectId = curse_project_id
		projectSlug = curseHomepageUrl.substring(curseHomepageUrl.lastIndexOf('/') + 1)
		accessToken.set(project.findProperty('curseforge_apikey') ?: '0')
		changelog.set(changelogHtml)
		changelogType = 'html'
		minecraftVersionRange {
			start = minecraft_version
			end = minecraft_version
		}
		javaVersions.add(JavaVersion.VERSION_1_8)
		client = true
		server = true
		dryRun = project.findProperty('curseforge_apikey') == null
	}

	modrinth {
		projectId = modrinthId
		accessToken = project.findProperty('modrinthToken')
		minecraftVersionRange {
			start = minecraft_version
			end = minecraft_version
		}
		dryRun = project.findProperty('modrinthToken') == null
	}
}

tasks.named('publishCurseforge') {
	dependsOn(makeChangelog)
}
tasks.named('publishModrinth') {
	dependsOn(makeMarkdownChangelog)
}

tasks.register('curseforge') {
	group = 'publishing'
	description = 'Publishes JEI to CurseForge.'
	dependsOn tasks.named('publishCurseforge')
}

tasks.register('modrinth') {
	group = 'publishing'
	description = 'Publishes JEI to Modrinth.'
	dependsOn tasks.named('publishModrinth')
}

jar {
	from sourceSets.main.output
	from sourceSets.api.output

	manifest.attributes([
			'Specification-Title'     : 'Just Enough Items',
			'Specification-Vendor'    : 'mezz',
			'Specification-Version'   : "${semver}",
			'Implementation-Title'    : project.name,
			'Implementation-Version'  : "${project.version}",
			'Implementation-Vendor'   : 'mezz',
			'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
			"Automatic-Module-Name": "mezz.jei",
	])

	finalizedBy 'reobfJar'
}

task javadocJar(type: Jar, dependsOn: javadoc) {
	duplicatesStrategy(DuplicatesStrategy.FAIL)
	archiveClassifier.set('javadoc')
	from javadoc.destinationDir
}

task sourcesJar(type: Jar) {
	duplicatesStrategy(DuplicatesStrategy.FAIL)
	archiveClassifier.set('sources')
	from sourceSets.main.allJava
	from sourceSets.api.allJava
}

def apiJarTask = tasks.register('apiJar', Jar) {
	duplicatesStrategy(DuplicatesStrategy.FAIL)
	archiveClassifier.set('api')
	from sourceSets.api.output

	// TODO: when FG bug is fixed, remove allJava from the api jar.
	// https://github.com/MinecraftForge/ForgeGradle/issues/369
	// Gradle should be able to pull them from the -sources jar.
	from sourceSets.api.allJava
}

task deobfJar(type: Jar) {
	duplicatesStrategy(DuplicatesStrategy.FAIL)
	archiveClassifier.set('deobf')
	from sourceSets.main.output
	from sourceSets.api.output
}

artifacts {
	archives javadocJar
	archives sourcesJar
	archives apiJarTask
	archives deobfJar
}

reobf {
	apiJar { classpath.from(sourceSets.api.compileClasspath) }
	jar { classpath.from(sourceSets.main.compileClasspath) }
}

apiJarTask.configure {
	finalizedBy tasks.named('reobfApiJar')
}

tasks.register('reobf') {
	dependsOn reobfJar
	dependsOn reobfApiJar
}

publishing {
	publications { PublicationContainer publicationContainer ->
		publicationContainer.register("maven", MavenPublication) { MavenPublication publication ->
			artifact(apiJarTask)
			artifact(jar)
			artifact(javadocJar)
			artifact(deobfJar)
			artifact(sourcesJar)
		}
	}
	repositories {
		if (project.hasProperty('DEPLOY_DIR')) {
			maven { url DEPLOY_DIR }
		}
	}
}

idea {
	module {
		for (String exclude in ['run', 'out', 'logs']) {
			excludeDirs += file(exclude)
		}
	}
}

test {
	useJUnitPlatform()
	include 'mezz/jei/**'
	exclude 'mezz/jei/lib/**'
}

apply from: 'buildtools/ApiCompatibility.gradle'
