# Gradle settings
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
# This setting speeds up running single tasks from subprojects by only configuring what's needed.
# see https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html
# Disabled because this breaks Gradle tasks in older toolchains
org.gradle.configureondemand=false
org.gradle.caching=true
# VanillaGradle does not support configuration cache
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn

# JEI
modName=Just Enough Items
modId=jei
modAuthor=mezz
# http://maven.apache.org/guides/mini/guide-naming-conventions.html
modGroup=mezz.jei
modDescription=JEI is an item and recipe viewing mod for Minecraft, built from the ground up for stability and performance.
# Mojang ships Java 17 to end users in 1.18+
modJavaVersion=17
githubUrl=https://github.com/mezz/JustEnoughItems

# Minecraft
minecraftVersion=1.19.2
minecraftVersionRange=[1.19, 1.19.2]

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.2.html
forgeVersion=43.5.0
forgeLoaderVersionRange=[41,)
forgeVersionRange=[41.0.94,)

# Fabric
# https://fabricmc.net/develop/
fabricLoaderVersion=0.19.4
fabricApiVersion=0.77.0+1.19.2

# AMECS (Fabric only, for keybinds with modifiers)
# https://maven.siphalor.de/de/siphalor/amecs/amecs-api-legacy/amecs-api-legacy-mc1.19.0/maven-metadata.xml
amecsMinecraftVersion=mc1.19.0
amecsVersionFabric=1.8.2
amecsKeyModifiersVersionFabric=1.0.2

# Mappings
# https://parchmentmc.org/docs/getting-started
parchmentMinecraftVersion=1.19.2
parchmentVersionForge=1.19.2-2022.11.27-1.19.2
parchmentVersionFabric=2022.11.27

# Publishing
curseProjectId=238222
curseHomepageUrl=https://www.curseforge.com/minecraft/mc-mods/jei
modrinthId=u6dRKJwZ

# Test
jUnitVersion=6.1.3
bakedSubstringIndexVersion=0.1.0

# Version
specificationVersion=11.51.0
