[project]
name = "jenkins-github-release-comments"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = []

[tool.pyright]
pythonVersion = "3.10"
include = [
    ".jenkins/githubReleaseComments.py",
    ".jenkins/test_githubReleaseComments.py",
]
exclude = [
    "**/build",
    ".gradle",
    ".idea",
]
