pipeline {
    agent any
    tools {
        jdk "jdk8u292-b10"
    }

    environment {
      ORG_GRADLE_PROJECT_curseforge_apikey = credentials("jei-curseforge-key")
      ORG_GRADLE_PROJECT_modrinthToken = credentials("modrinth-auth-token")
      ORG_GRADLE_PROJECT_BUILD_NUMBER = "${env.BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh "rm -rf build/libs"
            }
        }

        stage('Test') {
            steps {
                sh "./gradlew test --no-daemon"
            }
        }

        stage('Build') {
            steps {
                sh "./gradlew build --no-daemon"
            }
        }

        stage('Archive') {
            steps {
                junit allowEmptyResults: true, testResults: 'build/test-results/**/*.xml'
            }
        }

        stage('Publish Maven') {
            steps {
                sh "./gradlew publish -PDEPLOY_DIR=${env.MAVEN_DEPLOY_DIR} --no-daemon"
            }
        }

        stage('Publish CurseForge') {
            steps {
                sh "./gradlew publishCurseForge --no-daemon"
            }
        }

        stage('Publish Modrinth') {
            steps {
                sh "./gradlew modrinth --no-daemon"
            }
        }
    }
}
