name: 'Build and Test'

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Validate wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: false

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy together artifacts
        shell: bash
        run: |
          mkdir dist
          cp Common/build/libs/*.jar dist
          cp CommonApi/build/libs/*.jar dist
          cp Core/build/libs/*.jar dist
          cp Fabric/build/libs/*.jar dist
          cp FabricApi/build/libs/*.jar dist
          cp Forge/build/libs/*.jar dist
          cp ForgeApi/build/libs/*.jar dist
          cp NeoForge/build/libs/*.jar dist
          cp NeoForgeApi/build/libs/*.jar dist
          cp Gui/build/libs/*.jar dist
          cp Library/build/libs/*.jar dist

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: dist/*
